---
  - name: Remove old versions
    apt:
      pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
      state: absent
    become: yes

  - name: Install stuff
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      update_cache: yes
    become: yes

  - name: obtain key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    become: yes

  - name: add stable release repo
    shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    become: yes

  - name: install docker ce
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      update_cache: yes
    become: yes

...
